'use strict';

const fs = require('fs').promises;
const path = require('path');
const logger = require('../logger');

class ReportGenerator {
  constructor() {
    this.reportsDir = './reports';
    this.ensureReportsDir();
  }

  async ensureReportsDir() {
    await fs.mkdir(this.reportsDir, { recursive: true }).catch(() => {});
  }

  /**
   * Generate comprehensive accessibility report
   */
  async generateReport(data) {
    try {
      const {
        jobId,
        filename,
        pdfInfo,
        accessibilityIssues,
        remediationResult,
        wcagLevel,
        status,
        pythonEnhanced = false,
      } = data;

      const actualLevel = wcagLevel || 'AA';
      const generatedAt = new Date().toISOString();

      const reportPath = path.join(this.reportsDir, `${jobId}-report.html`);
      const dataPath = path.join(this.reportsDir, `${jobId}-data.json`);

      // Save raw JSON data for export endpoints
      const reportData = {
        jobId,
        filename,
        pdfInfo,
        accessibilityIssues,
        remediationResult,
        wcagLevel: actualLevel,
        status,
        pythonEnhanced,
        generatedAt,
      };
      await fs.writeFile(dataPath, JSON.stringify(reportData, null, 2), 'utf8');

      const htmlContent = this.generateHTML({
        jobId,
        filename,
        pdfInfo,
        accessibilityIssues,
        remediationResult,
        wcagLevel: actualLevel,
        status,
        pythonEnhanced,
        generatedAt,
      });

      await fs.writeFile(reportPath, htmlContent, 'utf8');

      logger.info({ reportPath }, 'Report generated');
      return reportPath;

    } catch (error) {
      logger.error({ err: error.message }, 'Error generating report');
      throw new Error(`Failed to generate report: ${error.message}`);
    }
  }

  /**
   * Generate HTML content for the report
   */
  generateHTML(data) {
    const {
      jobId,
      filename,
      pdfInfo,
      accessibilityIssues,
      remediationResult,
      wcagLevel,
      status,
      pythonEnhanced = false,
      generatedAt,
    } = data;

    const issuesBySeverity = this.groupIssuesBySeverity(accessibilityIssues);
    const issuesByWCAG = this.groupIssuesByWCAG(accessibilityIssues);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Accessibility Report - ${filename}</title>
    <style>
        ${this.getCSS()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>PDF Accessibility Report</h1>
            <div class="report-meta">
                <div class="meta-item">
                    <strong>File:</strong> ${filename}
                </div>
                <div class="meta-item">
                    <strong>WCAG Level:</strong> ${wcagLevel}
                </div>
                <div class="meta-item">
                    <strong>Status:</strong> <span class="status status-${status}">${status.toUpperCase()}</span>
                </div>
                <div class="meta-item">
                    <strong>Generated:</strong> ${new Date(generatedAt).toLocaleString()}
                </div>
                <div class="meta-item">
                    <strong>Job ID:</strong> ${jobId}
                </div>
                <div class="meta-item">
                    <strong>Analysis:</strong>
                    <span class="status status-${pythonEnhanced ? 'analyzed' : 'processing'}">
                        ${pythonEnhanced ? 'Python-enhanced (pikepdf + pdfplumber)' : 'Basic (Python unavailable)'}
                    </span>
                </div>
            </div>
        </header>

        ${this.generateSummarySection(accessibilityIssues, remediationResult)}
        
        ${pdfInfo ? this.generateDocumentInfoSection(pdfInfo) : ''}
        
        ${this.generateIssuesOverviewSection(issuesBySeverity, issuesByWCAG)}
        
        ${this.generateDetailedIssuesSection(accessibilityIssues)}
        
        ${remediationResult ? this.generateRemediationSection(remediationResult) : ''}
        
        ${this.generateRecommendationsSection(accessibilityIssues, wcagLevel)}
        
        ${this.generateWCAGGuidelinesSection(wcagLevel)}
        
        <footer class="footer">
            <p>Generated by PDF Accessibility Tool v1.0</p>
            <p>For support and documentation, visit our help center.</p>
        </footer>
    </div>
</body>
</html>`;
  }

  /**
   * Generate summary section
   */
  generateSummarySection(issues, remediationResult) {
    const totalIssues = issues.length;
    const criticalIssues = issues.filter(i => i.severity === 'critical').length;
    const moderateIssues = issues.filter(i => i.severity === 'moderate').length;
    const minorIssues = issues.filter(i => i.severity === 'minor').length;

    let complianceLevel = 'Non-Compliant';
    if (criticalIssues === 0 && moderateIssues === 0) {
      complianceLevel = 'Fully Compliant';
    } else if (criticalIssues === 0) {
      complianceLevel = 'Partially Compliant';
    }

    return `
        <section class="summary">
            <h2>Executive Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <div class="summary-number">${totalIssues}</div>
                    <div class="summary-label">Total Issues</div>
                </div>
                <div class="summary-card critical">
                    <div class="summary-number">${criticalIssues}</div>
                    <div class="summary-label">Critical</div>
                </div>
                <div class="summary-card moderate">
                    <div class="summary-number">${moderateIssues}</div>
                    <div class="summary-label">Moderate</div>
                </div>
                <div class="summary-card minor">
                    <div class="summary-number">${minorIssues}</div>
                    <div class="summary-label">Minor</div>
                </div>
            </div>
            
            <div class="compliance-status">
                <h3>Compliance Status</h3>
                <div class="compliance-badge compliance-${complianceLevel.toLowerCase().replace(' ', '-')}">
                    ${complianceLevel}
                </div>
                <p class="compliance-description">
                    ${this.getComplianceDescription(complianceLevel, criticalIssues, moderateIssues)}
                </p>
            </div>
            
            ${remediationResult ? this.generateRemediationSummary(remediationResult) : ''}
        </section>`;
  }

  /**
   * Generate document info section
   */
  generateDocumentInfoSection(pdfInfo) {
    return `
        <section class="document-info">
            <h2>Document Information</h2>
            <div class="info-grid">
                <div class="info-item">
                    <strong>Title:</strong> ${pdfInfo.title || 'Not specified'}
                </div>
                <div class="info-item">
                    <strong>Author:</strong> ${pdfInfo.author || 'Not specified'}
                </div>
                <div class="info-item">
                    <strong>Subject:</strong> ${pdfInfo.subject || 'Not specified'}
                </div>
                <div class="info-item">
                    <strong>Keywords:</strong> ${pdfInfo.keywords || 'Not specified'}
                </div>
                <div class="info-item">
                    <strong>Pages:</strong> ${pdfInfo.pageCount}
                </div>
                <div class="info-item">
                    <strong>Word Count:</strong> ${pdfInfo.wordCount?.toLocaleString() || 'Unknown'}
                </div>
                <div class="info-item">
                    <strong>File Size:</strong> ${this.formatFileSize(pdfInfo.fileSize)}
                </div>
                <div class="info-item">
                    <strong>Creation Date:</strong> ${pdfInfo.creationDate ? new Date(pdfInfo.creationDate).toLocaleDateString() : 'Unknown'}
                </div>
            </div>
        </section>`;
  }

  /**
   * Generate issues overview section
   */
  generateIssuesOverviewSection(issuesBySeverity, issuesByWCAG) {
    return `
        <section class="issues-overview">
            <h2>Issues Overview</h2>
            
            <div class="overview-charts">
                <div class="chart-container">
                    <h3>Issues by Severity</h3>
                    <div class="severity-chart">
                        ${Object.entries(issuesBySeverity).map(([severity, issues]) => `
                            <div class="severity-bar">
                                <div class="severity-label">${severity.charAt(0).toUpperCase() + severity.slice(1)}</div>
                                <div class="severity-count">${issues.length}</div>
                                <div class="severity-progress">
                                    <div class="severity-fill severity-${severity}" style="width: ${(issues.length / Math.max(...Object.values(issuesBySeverity).map(i => i.length))) * 100}%"></div>
                                </div>
                            </div>
                        `).join('')}
                    </div>
                </div>
                
                <div class="chart-container">
                    <h3>Issues by WCAG Guideline</h3>
                    <div class="wcag-chart">
                        ${Object.entries(issuesByWCAG).map(([rule, issues]) => `
                            <div class="wcag-item">
                                <span class="wcag-rule">${rule}</span>
                                <span class="wcag-count">${issues.length}</span>
                            </div>
                        `).join('')}
                    </div>
                </div>
            </div>
        </section>`;
  }

  /**
   * Generate detailed issues section
   */
  generateDetailedIssuesSection(issues) {
    if (issues.length === 0) {
      return `
        <section class="detailed-issues">
            <h2>Accessibility Issues</h2>
            <div class="no-issues">
                <p>✅ No accessibility issues found! This document appears to meet the selected WCAG standards.</p>
            </div>
        </section>`;
    }

    return `
        <section class="detailed-issues">
            <h2>Detailed Issues</h2>
            <div class="issues-list">
                ${issues.map((issue, index) => {
                  const wcagUrl = this.getWCAGRuleUrl(issue.wcagRule);
                  return `
                    <div class="issue-card severity-${issue.severity}">
                        <div class="issue-header">
                            <div class="issue-title">
                                <span class="issue-number">${index + 1}</span>
                                <h3>${issue.title}</h3>
                                <span class="severity-badge severity-${issue.severity}">${issue.severity.toUpperCase()}</span>
                            </div>
                            <div class="issue-meta">
                                <span class="wcag-rule">
                                  WCAG ${issue.wcagRule}
                                  ${wcagUrl ? `<a href="${wcagUrl}" target="_blank" rel="noopener" class="wcag-link">🔗</a>` : ''}
                                </span>
                                <span class="page-info">Page: ${issue.page}</span>
                                <span class="element-info">Element: ${issue.element}</span>
                            </div>
                        </div>
                        
                        <div class="issue-content">
                            <div class="issue-description">
                                <p>${issue.description}</p>
                            </div>
                            
                            <div class="issue-impact">
                                <strong>Impact:</strong> ${issue.impact}
                            </div>
                            
                            <div class="issue-fixable">
                                <strong>Auto-fixable:</strong> 
                                <span class="fixable-${issue.fixable}">
                                    ${issue.fixable ? '✅ Yes' : '❌ Manual review required'}
                                </span>
                            </div>
                            
                            ${issue.fixApplied ? `
                                <div class="fix-applied">
                                    <strong>✅ Fix Applied:</strong> ${issue.fixApplied}
                                    ${issue.fixDetails ? `<br><em>${issue.fixDetails}</em>` : ''}
                                </div>
                            ` : ''}
                            
                            ${issue.reason ? `
                                <div class="manual-reason">
                                    <strong>Manual Review Reason:</strong> ${issue.reason}
                                </div>
                            ` : ''}
                        </div>
                    </div>
                `}).join('')}
            </div>
        </section>`;
  }

  /**
   * Generate remediation section
   */
  generateRemediationSection(remediationResult) {
    if (!remediationResult) {
      return '';
    }

    const { summary, fixedIssues, remainingIssues } = remediationResult;

    return `
        <section class="remediation-results">
            <h2>Remediation Results</h2>
            
            <div class="remediation-summary">
                <div class="remediation-stats">
                    <div class="stat-card">
                        <div class="stat-number">${summary.fixedCount}</div>
                        <div class="stat-label">Issues Fixed</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number">${summary.remainingCount}</div>
                        <div class="stat-label">Require Manual Review</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-number">${summary.autoFixPercentage}%</div>
                        <div class="stat-label">Auto-Fix Success Rate</div>
                    </div>
                </div>
            </div>
            
            ${fixedIssues.length > 0 ? `
                <div class="fixed-issues">
                    <h3>✅ Automatically Fixed Issues</h3>
                    <div class="fixed-list">
                        ${fixedIssues.map(issue => `
                            <div class="fixed-item">
                                <strong>${issue.title}</strong>
                                <p>${issue.fixApplied}</p>
                                ${issue.fixDetails ? `<em>${issue.fixDetails}</em>` : ''}
                            </div>
                        `).join('')}
                    </div>
                </div>
            ` : ''}
            
            ${remainingIssues.length > 0 ? `
                <div class="remaining-issues">
                    <h3>⚠️ Issues Requiring Manual Review</h3>
                    <div class="remaining-list">
                        ${remainingIssues.map(issue => `
                            <div class="remaining-item">
                                <strong>${issue.title}</strong>
                                <p>${issue.reason}</p>
                            </div>
                        `).join('')}
                    </div>
                </div>
            ` : ''}
        </section>`;
  }

  /**
   * Generate recommendations section
   */
  generateRecommendationsSection(issues, wcagLevel) {
    const recommendations = this.generateRecommendations(issues, wcagLevel);
    
    return `
        <section class="recommendations">
            <h2>Recommendations</h2>
            <div class="recommendations-list">
                ${recommendations.map((rec, index) => `
                    <div class="recommendation-item">
                        <div class="rec-number">${index + 1}</div>
                        <div class="rec-content">
                            <h4>${rec.title}</h4>
                            <p>${rec.description}</p>
                            <div class="rec-priority priority-${rec.priority}">
                                Priority: ${rec.priority.toUpperCase()}
                            </div>
                        </div>
                    </div>
                `).join('')}
            </div>
        </section>`;
  }

  /**
   * Generate WCAG guidelines section
   */
  generateWCAGGuidelinesSection(wcagLevel) {
    return `
        <section class="wcag-guidelines">
            <h2>WCAG ${wcagLevel} Guidelines Reference</h2>
            <div class="guidelines-info">
                <p>This report evaluates your document against WCAG ${wcagLevel} standards. Below are the key principles:</p>
                
                <div class="principles-grid">
                    <div class="principle">
                        <h4>1. Perceivable</h4>
                        <p>Information must be presentable in ways users can perceive.</p>
                        <ul>
                            <li>Text alternatives for images</li>
                            <li>Captions and alternatives for multimedia</li>
                            <li>Content can be presented without losing meaning</li>
                            <li>Make it easier for users to see and hear content</li>
                        </ul>
                    </div>
                    
                    <div class="principle">
                        <h4>2. Operable</h4>
                        <p>Interface components must be operable by all users.</p>
                        <ul>
                            <li>All functionality available from keyboard</li>
                            <li>Users have enough time to read content</li>
                            <li>Content doesn't cause seizures</li>
                            <li>Users can navigate and find content</li>
                        </ul>
                    </div>
                    
                    <div class="principle">
                        <h4>3. Understandable</h4>
                        <p>Information and UI operation must be understandable.</p>
                        <ul>
                            <li>Text is readable and understandable</li>
                            <li>Content appears and operates predictably</li>
                            <li>Users are helped to avoid and correct mistakes</li>
                        </ul>
                    </div>
                    
                    <div class="principle">
                        <h4>4. Robust</h4>
                        <p>Content must be robust enough for various assistive technologies.</p>
                        <ul>
                            <li>Maximize compatibility with assistive technologies</li>
                            <li>Use valid, semantic markup</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>`;
  }

  /**
   * Generate remediation summary
   */
  generateRemediationSummary(remediationResult) {
    if (!remediationResult || !remediationResult.summary) {
      return '';
    }

    const { summary } = remediationResult;
    return `
        <div class="remediation-summary-inline">
            <h3>Remediation Summary</h3>
            <p>
                <strong>${summary.fixedCount}</strong> issues were automatically fixed out of 
                <strong>${summary.totalIssues}</strong> total issues 
                (<strong>${summary.autoFixPercentage}%</strong> success rate).
                ${summary.remainingCount > 0 ? 
                    `<strong>${summary.remainingCount}</strong> issues require manual review.` : 
                    'All fixable issues have been resolved.'
                }
            </p>
        </div>`;
  }

  /**
   * Group issues by severity
   */
  groupIssuesBySeverity(issues) {
    return issues.reduce((groups, issue) => {
      const severity = issue.severity || 'unknown';
      if (!groups[severity]) {
        groups[severity] = [];
      }
      groups[severity].push(issue);
      return groups;
    }, {});
  }

  /**
   * Group issues by WCAG rule
   */
  groupIssuesByWCAG(issues) {
    return issues.reduce((groups, issue) => {
      const rule = issue.wcagRule || 'Unknown';
      if (!groups[rule]) {
        groups[rule] = [];
      }
      groups[rule].push(issue);
      return groups;
    }, {});
  }

  /**
   * Get compliance description
   */
  getComplianceDescription(level, critical, moderate) {
    switch (level) {
      case 'Fully Compliant':
        return 'This document meets all evaluated WCAG standards with no critical or moderate issues found.';
      case 'Partially Compliant':
        return `This document has ${moderate} moderate issue(s) but no critical accessibility barriers.`;
      case 'Non-Compliant':
        return `This document has ${critical} critical issue(s) that must be addressed for accessibility compliance.`;
      default:
        return 'Compliance status could not be determined.';
    }
  }

  /**
   * Format file size
   */
  formatFileSize(bytes) {
    if (!bytes) {
      return 'Unknown';
    }
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    if (bytes === 0) {
      return '0 Bytes';
    }
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];
  }

  /**
   * Generate recommendations based on issues
   */
  generateRecommendations(issues, wcagLevel) {
    const recommendations = [];
    
    const criticalIssues = issues.filter(i => i.severity === 'critical');

    if (criticalIssues.length > 0) {
      recommendations.push({
        title: 'Address Critical Accessibility Issues',
        description: 'Focus on resolving critical issues first as they create significant barriers for users with disabilities.',
        priority: 'high'
      });
    }
    
    if (issues.some(i => i.id.startsWith('structure-'))) {
      recommendations.push({
        title: 'Improve Document Structure',
        description: 'Add proper headings, tags, and bookmarks to improve navigation for screen reader users.',
        priority: 'high'
      });
    }
    
    if (issues.some(i => i.id.startsWith('alt-text-'))) {
      recommendations.push({
        title: 'Add Alternative Text to Images',
        description: 'Provide meaningful descriptions for all images that convey information.',
        priority: 'high'
      });
    }
    
    if (issues.some(i => i.id.startsWith('contrast-'))) {
      recommendations.push({
        title: 'Review Color Contrast',
        description: 'Ensure all text meets minimum contrast ratios against background colors.',
        priority: 'medium'
      });
    }
    
    recommendations.push({
      title: 'Regular Accessibility Testing',
      description: 'Implement regular accessibility testing in your document creation workflow.',
      priority: 'medium'
    });
    
    if (wcagLevel === 'AAA') {
      recommendations.push({
        title: 'Enhanced AAA Compliance',
        description: 'Consider additional enhancements for AAA compliance including enhanced contrast and context-sensitive help.',
        priority: 'low'
      });
    }
    
    return recommendations;
  }

  /**
   * Helper to map WCAG rule numbers to URLs
   */
  getWCAGRuleUrl(rule) {
    if (!rule) {
      return null;
    }
    const mapping = {
      '1.1.1': 'non-text-content',
      '1.3.1': 'info-and-relationships',
      '1.3.2': 'meaningful-sequence',
      '1.4.3': 'contrast-minimum',
      '1.4.6': 'contrast-enhanced',
      '2.4.2': 'page-titled',
      '2.4.5': 'multiple-ways',
      '2.4.9': 'link-purpose-link-only',
      '2.4.10': 'section-headings',
      '3.1.1': 'language-of-page',
      '3.3.5': 'help',
      '4.1.2': 'name-role-value',
    };
    const fragment = mapping[rule];
    if (!fragment) {
      return null;
    }
    return `https://www.w3.org/WAI/WCAG21/Understanding/${fragment}.html`;
  }

  /**
   * Get CSS styles for the report
   */
  getCSS() {
    return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: white;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
        
        .header {
            border-bottom: 3px solid #007cba;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #007cba;
            margin-bottom: 15px;
            font-size: 2.5em;
        }
        
        .report-meta {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
        }
        
        .meta-item {
            padding: 10px;
            background: #f8f9fa;
            border-left: 4px solid #007cba;
        }
        
        .status {
            padding: 4px 8px;
            border-radius: 4px;
            font-weight: bold;
        }
        
        .status-analyzed { background: #e3f2fd; color: #1976d2; }
        .status-remediated { background: #e8f5e8; color: #388e3c; }
        
        .summary {
            margin-bottom: 40px;
        }
        
        .summary h2 {
            color: #007cba;
            margin-bottom: 20px;
            font-size: 2em;
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .summary-card {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            background: #f8f9fa;
            border: 2px solid #dee2e6;
        }
        
        .summary-card.critical { border-color: #dc3545; background: #f8d7da; }
        .summary-card.moderate { border-color: #fd7e14; background: #ffeeba; }
        .summary-card.minor { border-color: #28a745; background: #d4edda; }
        
        .summary-number {
            font-size: 2.5em;
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        .summary-label {
            font-size: 1.1em;
            color: #666;
        }
        
        .compliance-status {
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            text-align: center;
        }
        
        .compliance-badge {
            display: inline-block;
            padding: 10px 20px;
            border-radius: 25px;
            font-weight: bold;
            font-size: 1.2em;
            margin: 10px 0;
        }
        
        .compliance-fully-compliant { background: #d4edda; color: #155724; }
        .compliance-partially-compliant { background: #ffeeba; color: #856404; }
        .compliance-non-compliant { background: #f8d7da; color: #721c24; }
        
        .document-info, .issues-overview, .detailed-issues, .remediation-results, .recommendations, .wcag-guidelines {
            margin-bottom: 40px;
        }
        
        .document-info h2, .issues-overview h2, .detailed-issues h2, .remediation-results h2, .recommendations h2, .wcag-guidelines h2 {
            color: #007cba;
            margin-bottom: 20px;
            font-size: 1.8em;
            border-bottom: 2px solid #007cba;
            padding-bottom: 10px;
        }
        
        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 15px;
        }
        
        .info-item {
            padding: 15px;
            background: #f8f9fa;
            border-radius: 5px;
        }
        
        .overview-charts {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
        }
        
        .chart-container {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
        }
        
        .severity-bar {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        
        .severity-label {
            width: 80px;
            font-weight: bold;
        }
        
        .severity-count {
            width: 40px;
            text-align: center;
            font-weight: bold;
        }
        
        .severity-progress {
            flex: 1;
            height: 20px;
            background: #e9ecef;
            border-radius: 10px;
            margin-left: 10px;
            overflow: hidden;
        }
        
        .severity-fill {
            height: 100%;
            border-radius: 10px;
        }
        
        .severity-fill.severity-critical { background: #dc3545; }
        .severity-fill.severity-moderate { background: #fd7e14; }
        .severity-fill.severity-minor { background: #28a745; }
        
        .wcag-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #dee2e6;
        }
        
        .wcag-rule {
            font-weight: bold;
            color: #007cba;
        }
        
        .issue-card {
            border: 1px solid #dee2e6;
            border-radius: 8px;
            margin-bottom: 20px;
            overflow: hidden;
        }
        
        .issue-card.severity-critical { border-left: 5px solid #dc3545; }
        .issue-card.severity-moderate { border-left: 5px solid #fd7e14; }
        .issue-card.severity-minor { border-left: 5px solid #28a745; }
        
        .issue-header {
            background: #f8f9fa;
            padding: 15px;
            border-bottom: 1px solid #dee2e6;
        }
        
        .issue-title {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 10px;
        }
        
        .issue-number {
            background: #007cba;
            color: white;
            width: 30px;
            height: 30px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
        }
        
        .issue-title h3 {
            flex: 1;
            color: #333;
        }
        
        .severity-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            font-weight: bold;
        }
        
        .severity-badge.severity-critical { background: #dc3545; color: white; }
        .severity-badge.severity-moderate { background: #fd7e14; color: white; }
        .severity-badge.severity-minor { background: #28a745; color: white; }
        
        .issue-meta {
            display: flex;
            gap: 15px;
            flex-wrap: wrap;
        }
        
        .issue-meta span {
            background: #e9ecef;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.9em;
        }
        
        .issue-content {
            padding: 15px;
        }
        
        .issue-content > div {
            margin-bottom: 10px;
        }
        
        .fixable-true { color: #28a745; font-weight: bold; }
        .fixable-false { color: #dc3545; font-weight: bold; }
        
        .fix-applied {
            background: #d4edda;
            padding: 10px;
            border-radius: 5px;
            border-left: 4px solid #28a745;
        }
        
        .manual-reason {
            background: #ffeeba;
            padding: 10px;
            border-radius: 5px;
            border-left: 4px solid #fd7e14;
        }
        
        .no-issues {
            text-align: center;
            padding: 40px;
            background: #d4edda;
            border-radius: 8px;
            font-size: 1.2em;
        }
        
        .remediation-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .stat-card {
            text-align: center;
            padding: 20px;
            background: #e3f2fd;
            border-radius: 8px;
        }
        
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #1976d2;
        }
        
        .fixed-issues, .remaining-issues {
            margin-top: 20px;
        }
        
        .fixed-item, .remaining-item {
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 5px;
        }
        
        .fixed-item {
            background: #d4edda;
            border-left: 4px solid #28a745;
        }
        
        .remaining-item {
            background: #ffeeba;
            border-left: 4px solid #fd7e14;
        }
        
        .recommendations-list {
            display: grid;
            gap: 20px;
        }
        
        .recommendation-item {
            display: flex;
            gap: 15px;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
        }
        
        .rec-number {
            background: #007cba;
            color: white;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            flex-shrink: 0;
        }
        
        .rec-content h4 {
            margin-bottom: 10px;
            color: #333;
        }
        
        .rec-priority {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.9em;
            font-weight: bold;
            margin-top: 10px;
        }
        
        .priority-high { background: #f8d7da; color: #721c24; }
        .priority-medium { background: #ffeeba; color: #856404; }
        .priority-low { background: #d4edda; color: #155724; }
        
        .principles-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        
        .principle {
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            border-top: 4px solid #007cba;
        }
        
        .principle h4 {
            color: #007cba;
            margin-bottom: 10px;
        }
        
        .principle ul {
            margin-top: 10px;
            padding-left: 20px;
        }
        
        .principle li {
            margin-bottom: 5px;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #dee2e6;
            text-align: center;
            color: #666;
        }
        
        .wcag-link {
            margin-left: 5px;
            font-size: 0.8em;
            color: #007cba;
            text-decoration: none;
        }
        
        .wcag-link:hover {
            text-decoration: underline;
        }
        
        @media (max-width: 768px) {
            .overview-charts {
                grid-template-columns: 1fr;
            }
            
            .issue-meta {
                flex-direction: column;
            }
            
            .summary-grid {
                grid-template-columns: repeat(2, 1fr);
            }
        }
    `;
  }
}

module.exports = ReportGenerator;